const state={page:'picks',league:'ALL',market:'ALL',picks:[],props:[],parlay:new Map(),feed:'loading',lastUpdated:null};
const navItems=[['picks','Today','8'],['live','Live',''],['props','Props',''],['parlay','Parlay',''],['rankings','Power',''],['pro','SharpEdge Pro',''],['account','Account',''],['admin','Admin','']];
const meta={picks:['Today’s Edge','High-confidence picks across every major market.'],live:['Live Board','Games in progress and the latest available lines.'],props:['Player Props','Filtered prop opportunities with model confidence.'],parlay:['Parlay Builder','Build a card from SharpEdge selections.'],rankings:['Power Rankings','Model-based team strength snapshot.'],pro:['SharpEdge Pro','Unlock the full betting intelligence dashboard.'],account:['Your Account','Membership and preference settings.'],admin:['Admin Center','Manage data health, featured picks, and publication status.']};
const demoPicks=[
{id:'nfl1',league:'NFL',matchup:'Kansas City vs Buffalo',market:'Moneyline',selection:'Kansas City ML',odds:'-130',decimal:1.77,confidence:84,edge:'+6.8%',reasons:['QB efficiency','Home field','Line value'],status:'pregame'},
{id:'nfl2',league:'NFL',matchup:'Philadelphia vs Dallas',market:'Spread',selection:'Philadelphia -3.5',odds:'-110',decimal:1.91,confidence:78,edge:'+4.1%',reasons:['Rush matchup','Pressure rate'],status:'pregame'},
{id:'nba1',league:'NBA',matchup:'Boston vs New York',market:'Total',selection:'Over 221.5',odds:'-108',decimal:1.93,confidence:76,edge:'+3.7%',reasons:['Pace','Shot profile'],status:'pregame'},
{id:'nba2',league:'NBA',matchup:'Denver vs Phoenix',market:'Moneyline',selection:'Denver ML',odds:'-125',decimal:1.80,confidence:81,edge:'+5.2%',reasons:['Rest advantage','Half-court rating'],status:'pregame'},
{id:'mlb1',league:'MLB',matchup:'Los Angeles vs San Diego',market:'Moneyline',selection:'Los Angeles ML',odds:'-145',decimal:1.69,confidence:82,edge:'+5.9%',reasons:['Starter edge','Bullpen form'],status:'pregame'},
{id:'mlb2',league:'MLB',matchup:'New York vs Boston',market:'Total',selection:'Under 9.0',odds:'-105',decimal:1.95,confidence:74,edge:'+2.8%',reasons:['Weather','Starter command'],status:'pregame'},
{id:'soc1',league:'SOCCER',matchup:'Madrid vs Sevilla',market:'Moneyline',selection:'Madrid ML',odds:'-155',decimal:1.65,confidence:83,edge:'+6.1%',reasons:['xG advantage','Home form'],status:'pregame'},
{id:'soc2',league:'SOCCER',matchup:'Manchester vs London',market:'Total',selection:'Over 2.5 Goals',odds:'+105',decimal:2.05,confidence:72,edge:'+2.3%',reasons:['Chance creation','Recent scoring'],status:'pregame'}];
const demoProps=[
{id:'p1',league:'NBA',player:'Primary Guard',matchup:'Denver vs Phoenix',market:'Points',selection:'Over 24.5 points',odds:'-115',confidence:79,edge:'+4.5%'},
{id:'p2',league:'NBA',player:'Starting Center',matchup:'Boston vs New York',market:'Rebounds',selection:'Over 9.5 rebounds',odds:'-110',confidence:77,edge:'+3.8%'},
{id:'p3',league:'NFL',player:'WR1',matchup:'Kansas City vs Buffalo',market:'Receiving',selection:'Over 69.5 yards',odds:'-105',confidence:75,edge:'+3.1%'},
{id:'p4',league:'MLB',player:'Leadoff Hitter',matchup:'Los Angeles vs San Diego',market:'Hits',selection:'1+ hit',odds:'-170',confidence:81,edge:'+4.9%'}];
function el(id){return document.getElementById(id)}
function toast(msg){const t=el('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function renderNav(){el('nav').innerHTML=navItems.map(([id,label,badge])=>`<button data-page="${id}" class="${state.page===id?'active':''}"><span>•</span><span>${label}</span>${badge?`<b class="badge">${badge}</b>`:''}</button>`).join('');el('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()})}
function setHeader(){const [t,s]=meta[state.page];el('pageTitle').textContent=t;el('pageSubtitle').textContent=s}
function metric(label,value){return `<div class="metric"><span>${label}</span><strong>${value}</strong></div>`}
function filters(){const leagues=['ALL','NFL','NBA','MLB','SOCCER'];const markets=['ALL','Moneyline','Spread','Total'];return `<div class="filters">${leagues.map(x=>`<button class="chip ${state.league===x?'active':''}" data-league="${x}">${x==='ALL'?'All Sports':x}</button>`).join('')}${markets.map(x=>`<button class="chip ${state.market===x?'active':''}" data-market="${x}">${x==='ALL'?'All Markets':x}</button>`).join('')}</div>`}
function pickCard(p){const inParlay=state.parlay.has(p.id);return `<article class="card"><div class="pick-top"><div><div class="league">${p.league} • ${p.market}</div><div class="matchup">${p.matchup}</div><div class="selection">${p.selection}</div></div><div class="odds"><span>Odds</span><strong>${p.odds}</strong></div></div><div class="confidence"><div class="conf-row"><span>SharpEdge confidence</span><b>${p.confidence}%</b></div><div class="bar"><i style="width:${Math.max(0,Math.min(100,p.confidence))}%"></i></div></div><div class="reasons">${(p.reasons||[]).map(r=>`<span class="reason">${r}</span>`).join('')}</div><div class="card-actions"><span class="edge">Model edge ${p.edge||'—'}</span><button class="btn small ${inParlay?'ghost':'gold'}" data-add="${p.id}">${inParlay?'Remove':'Add to Parlay'}</button></div></article>`}
function picksPage(){const picks=state.picks.filter(p=>(state.league==='ALL'||p.league===state.league)&&(state.market==='ALL'||p.market===state.market));const avg=Math.round(state.picks.reduce((a,p)=>a+p.confidence,0)/Math.max(1,state.picks.length));return `<div class="hero-grid">${metric('Top confidence',Math.max(...state.picks.map(p=>p.confidence),0)+'%')}${metric('Featured picks',state.picks.length)}${metric('Avg confidence',avg+'%')}${metric('Data feed',state.feed==='live'?'LIVE':'DEMO')}</div>${filters()}<div class="grid">${picks.length?picks.map(pickCard).join(''):`<div class="empty">No picks match these filters.</div>`}</div><div class="notice" style="margin-top:18px">Confidence is a model estimate, not a guarantee. Odds can move after publication.</div>`}
function livePage(){const live=state.picks.filter(p=>p.status==='live');return live.length?`<div class="grid">${live.map(pickCard).join('')}</div>`:`<div class="empty"><h3>No live games in the current feed</h3><p>SharpEdge will automatically show active games here when the connected provider reports them.</p></div>`}
function propsPage(){return `<div class="hero-grid">${metric('Tracked props',state.props.length)}${metric('Top prop confidence',Math.max(...state.props.map(p=>p.confidence),0)+'%')}${metric('Sports covered',new Set(state.props.map(p=>p.league)).size)}${metric('Feed',state.feed==='live'?'LIVE':'DEMO')}</div><div class="grid">${state.props.map(p=>`<article class="card"><div class="league">${p.league} • ${p.market}</div><div class="matchup">${p.matchup}</div><div class="selection">${p.player}: ${p.selection}</div><div class="confidence"><div class="conf-row"><span>Confidence</span><b>${p.confidence}%</b></div><div class="bar"><i style="width:${p.confidence}%"></i></div></div><div class="card-actions"><span class="edge">Model edge ${p.edge}</span><strong>${p.odds}</strong></div></article>`).join('')}</div>`}
function parlayPage(){const legs=[...state.parlay.values()];const decimal=legs.reduce((a,p)=>a*(p.decimal||1),1);const avg=legs.length?Math.round(legs.reduce((a,p)=>a+p.confidence,0)/legs.length):0;const american=decimal<=1?'-':decimal>=2?`+${Math.round((decimal-1)*100)}`:`-${Math.round(100/(decimal-1))}`;return `<div class="card"><div class="panel-title"><div><h2>Your SharpEdge Parlay</h2><p>Use only the plays you actually want together.</p></div><button class="btn small ghost" id="clearParlay">Clear</button></div>${legs.length?legs.map(p=>`<div class="parlay-leg"><div><b>${p.selection}</b><small>${p.league} • ${p.matchup}</small></div><strong>${p.odds}</strong></div>`).join(''):`<div class="empty">Add picks from Today’s Edge to build a parlay.</div>`}${legs.length?`<div class="summary"><div><span>Legs</span><strong>${legs.length}</strong></div><div><span>Est. odds</span><strong>${american}</strong></div><div><span>Avg confidence</span><strong>${avg}%</strong></div></div>`:''}</div><div class="notice" style="margin-top:14px">Adding more legs increases payout potential but lowers the chance the full parlay wins.</div>`}
function rankingsPage(){const rows=[['NFL','Kansas City','91'],['NFL','Philadelphia','88'],['NBA','Boston','92'],['NBA','Denver','89'],['MLB','Los Angeles','90'],['SOCCER','Madrid','91']];return `<div class="card"><div class="panel-title"><div><h2>Model Power Index</h2><p>Illustrative ranking layer ready to connect to your team-rating model.</p></div></div><table class="table"><thead><tr><th>League</th><th>Team</th><th>Power</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div>`}
function proPage(){return `<div class="grid"><div class="plan-card"><div class="league">FREE</div><h2>SharpEdge Basic</h2><div class="plan-price">$0 <span>/ month</span></div><ul class="feature-list"><li>Limited daily picks</li><li>Basic game board</li><li>Parlay builder</li></ul><button class="btn ghost">Current Plan</button></div><div class="plan-card featured"><div class="league">PRO</div><h2>SharpEdge Pro</h2><div class="plan-price">$19.99 <span>/ month</span></div><ul class="feature-list"><li>All AI picks and confidence scores</li><li>Moneyline, spread, total and props</li><li>Line movement and model edge</li><li>Injury and lineup context</li><li>Premium parlays</li></ul><button class="btn gold" id="checkoutBtn">Subscribe with Stripe</button></div></div><div class="notice" style="margin-top:14px">Stripe checkout activates automatically when STRIPE_SECRET_KEY and STRIPE_PRICE_ID are configured on Vercel.</div>`}
function accountPage(){return `<div class="card"><div class="panel-title"><div><h2>Profile & Preferences</h2><p>The UI is ready for Supabase Auth-backed accounts.</p></div></div><div class="form-grid"><div class="field"><label>Email</label><input value="member@example.com" disabled></div><div class="field"><label>Plan</label><input value="Free" disabled></div><div class="field"><label>Favorite sport</label><select><option>NFL</option><option>NBA</option><option>MLB</option><option>Soccer</option></select></div><div class="field"><label>Default market</label><select><option>All markets</option><option>Moneyline</option><option>Spread</option><option>Total</option><option>Props</option></select></div></div></div>`}
function adminPage(){return `<div class="hero-grid">${metric('Frontend','READY')}${metric('Games API',state.feed==='live'?'CONNECTED':'FALLBACK')}${metric('Props API',state.feed==='live'?'CONNECTED':'FALLBACK')}${metric('Deployment','VERCEL')}</div><div class="card"><div class="panel-title"><div><h2>Release Health</h2><p>One place to verify the app before publishing.</p></div></div><table class="table"><tbody><tr><td>Sports data provider</td><td><b>${state.feed==='live'?'Connected':'Using safe demo fallback'}</b></td></tr><tr><td>Last refresh</td><td>${state.lastUpdated?new Date(state.lastUpdated).toLocaleString():'Not yet'}</td></tr><tr><td>Games endpoint</td><td>/api/games</td></tr><tr><td>Props endpoint</td><td>/api/props</td></tr><tr><td>Health endpoint</td><td>/api/health</td></tr></tbody></table><div class="notice" style="margin-top:14px">No API secret is exposed in browser code. Provider and payment keys stay server-side in Vercel environment variables.</div></div>`}
function bind(){document.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{state.league=b.dataset.league;renderContent()});document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>{state.market=b.dataset.market;renderContent()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=state.picks.find(x=>x.id===b.dataset.add);if(!p)return;if(state.parlay.has(p.id)){state.parlay.delete(p.id);toast('Removed from parlay')}else{state.parlay.set(p.id,p);toast('Added to parlay')}renderContent()});const c=el('clearParlay');if(c)c.onclick=()=>{state.parlay.clear();renderContent();toast('Parlay cleared')};const checkout=el('checkoutBtn');if(checkout)checkout.onclick=async()=>{checkout.disabled=true;checkout.textContent='Opening checkout…';try{const r=await fetch('/api/checkout',{method:'POST'});const d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||'Checkout unavailable');location.href=d.url}catch(e){toast(e.message||'Checkout is not configured');checkout.disabled=false;checkout.textContent='Subscribe with Stripe'}}}
function renderContent(){const pages={picks:picksPage,live:livePage,props:propsPage,parlay:parlayPage,rankings:rankingsPage,pro:proPage,account:accountPage,admin:adminPage};el('content').innerHTML=pages[state.page]();bind()}
function render(){renderNav();setHeader();renderContent()}
function normalizeGame(g,i){const league=(g.league||g.sport||'SPORT').toUpperCase();const home=g.home_team||g.homeTeam||g.home||'Home';const away=g.away_team||g.awayTeam||g.away||'Away';const market=g.market||g.pick_market||'Moneyline';const selection=g.selection||g.pick||g.favorite||home;const odds=String(g.odds||g.price||'-110');const conf=Number(g.confidence||g.model_confidence||70);return{id:g.id||`live-${i}`,league,matchup:`${away} vs ${home}`,market,selection,odds,decimal:Number(g.decimal||1.91),confidence:Number.isFinite(conf)?Math.max(50,Math.min(95,Math.round(conf))):70,edge:g.edge||'+2.0%',reasons:g.reasons||['Live provider data'],status:(g.status||'pregame').toLowerCase()}}
async function loadData(){state.feed='loading';try{const [gr,pr]=await Promise.all([fetch('/api/games',{cache:'no-store'}),fetch('/api/props',{cache:'no-store'})]);const gd=await gr.json();const pd=await pr.json();if(gr.ok&&Array.isArray(gd.games)&&gd.games.length){state.picks=gd.games.map(normalizeGame);state.feed=gd.source==='provider'?'live':'demo'}else{state.picks=demoPicks;state.feed='demo'}if(pr.ok&&Array.isArray(pd.props)&&pd.props.length){state.props=pd.props}else state.props=demoProps}catch{state.picks=demoPicks;state.props=demoProps;state.feed='demo'}state.lastUpdated=Date.now();el('apiStatus').textContent=state.feed==='live'?'Sports feed connected':'Demo-safe mode active';render()}
el('refreshBtn').onclick=()=>{toast('Refreshing SharpEdge data…');loadData()};el('proBtn').onclick=()=>{state.page='pro';render()};render();loadData();
