-- Run once in Supabase SQL Editor
create table if not exists public.saved_picks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  pick_key text not null,
  pick_data jsonb not null,
  created_at timestamptz not null default now(),
  unique(user_id, pick_key)
);

alter table public.saved_picks enable row level security;

create policy "Users can read own saved picks"
on public.saved_picks for select
using (auth.uid() = user_id);

create policy "Users can insert own saved picks"
on public.saved_picks for insert
with check (auth.uid() = user_id);

create policy "Users can delete own saved picks"
on public.saved_picks for delete
using (auth.uid() = user_id);
